print('======= ABC STORE =======')
print('Item', 'Qty', 'Price', sep='      ')
print('-------------------------')
print('Apple', 2, 100, sep='       ')
print('Milk ', 1,  150, sep='       ')
print('Bread', 1, 120, sep='       ')
print('-------------------------')
print('Total:', 370, sep="              ")
print('Thankyou! Visit again')